---
- hosts: all
  become: true
  become_method: sudo

  pre_tasks:
    - name: Update package manager cache
      apt: update_cache=yes

    - name: Install required packages
      apt: name={{ item }} state=present
      with_items:
        - python
        - python-mysqldb
        - git
        - memcached

  roles:
    - setup
