---
- name: Creating new subscription
  command: "{{ plesk_subscription }}
      --create '{{ site.domain }}'
      -owner '{{ site.owner | default(default_owner) }}'
      -service_plan '{{ site.plan | default(default_plan) }}'
      -ip {{ site.ip_address | default(default_ip_address) }}
      -login {{ site.username }}
      -passwd '{{ site_password }}'"
  args:
    chdir: "{{ plesk_command_directory }}"
    creates: "{{ subscription_directory }}"

- name: Creating subdomain
  command: "{{ plesk_subdomain }}
      --create {{ site.subdomain }}
      -domain '{{ site.domain }}'
      -www-root '{{ site.root }}'
      -php true"
  args:
    chdir: "{{ plesk_command_directory }}"
    creates: "{{ site_directory }}"
  when: site.subdomain is defined

- name: Creating domain alias
  command: "{{ plesk_alias }}
      --create {{ site.alias }}
      -domain {{ site.domain }}
      -seo-redirect none"
  when: site.alias is defined

- name: Detecting whether Let's Encrypt certificate is installed
  stat: path="{{ lets_encrypt_directory }}/{{ site.domain }}"
  register: lets_encrypt_present
  when: site.lets_encrypt is defined

- name: Installing security certificate from Let's Encrypt
  command: "{{ lets_encrypt_command }}
      --email {{ site.lets_encrypt }}
      --domain {{ site.domain }}"
  when: site.lets_encrypt is defined and lets_encrypt_present is not defined
